<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Based on work from github.com/frou/GoFeather and github.com/DisposaBoy/GoSublime</string>
	<key>fileTypes</key>
	<array>
		<string>ly</string>
	</array>
	<key>firstLineMatch</key>
	<string>-[*]-( Mode:)? Lucy -[*]-</string>
	<key>name</key>
	<string>LucySublime: Lucy</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.ly</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>\z</string>
			<key>name</key>
			<string>comment.line.double-slash.ly</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ly</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.ly</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_placeholder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|none)\b</string>
			<key>name</key>
			<string>constant.language.ly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((\d+\.(\d+)?([eE][+-]?\d+)?|\d+[eE][+-]?\d+|\.\d+([eE][+-]?\d+)?)i?)\b</string>
			<key>name</key>
			<string>constant.numeric.floating-point.ly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\d+i|0[xX][0-9A-Fa-f]+|0[0-7]*|[1-9][0-9]*)\b</string>
			<key>name</key>
			<string>constant.numeric.integer.ly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'(?:[^'\\]|\\(?:\\|[abfnrtv']|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|U[0-9a-fA-F]{8}|[0-7]{3}))'</string>
			<key>name</key>
			<string>constant.other.rune.ly</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>A subset of keyword.other.ly for flow control keywords.</string>
			<key>match</key>
			<string>\b(break|continue|else|for|while|if|return)\b</string>
			<key>name</key>
			<string>keyword.control.ly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(break|case|continue|else|for|while|func|ly|if|import|return|var)\b</string>
			<key>name</key>
			<string>keyword.other.ly</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.other.ly</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.initialize.ly</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>This matches the 'x := 0' style of variable declaration.</string>
			<key>match</key>
			<string>(?:[[:alpha:]_][[:alnum:]_]*)(?:,\s+[[:alpha:]_][[:alnum:]_]*)*\s*(:=)</string>
			<key>name</key>
			<string>meta.initialization.short.ly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=(\Afunc|...\))\s)\b(\w+)\b(?=\()</string>
			<key>name</key>
			<string>entity.name.function.ly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=(\sfunc|....\))\s)\b(\w+)\b(?=\()</string>
			<key>name</key>
			<string>entity.name.function.ly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((\w+::)?\w+)\b(?=\()</string>
			<key>name</key>
			<string>support.function.ly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&lt;-)</string>
			<key>name</key>
			<string>keyword.operator.channel.ly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|!=|&lt;|&lt;=|&gt;|&gt;=)</string>
			<key>name</key>
			<string>keyword.operator.comparison.ly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&amp;&amp;|[|]{2}|!)</string>
			<key>name</key>
			<string>keyword.operator.logical.ly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([+]{2})</string>
			<key>name</key>
			<string>keyword.operator.increment.ly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(--)</string>
			<key>name</key>
			<string>keyword.decrement.ly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=|(?:[+]|-|[|]|^|[*]|/|%|&lt;&lt;|&gt;&gt;|&amp;|&amp;^)=)</string>
			<key>name</key>
			<string>keyword.operator.assignment.ly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([+]|-|[*]|/|%|&amp;|[|]|^|&amp;^|&lt;&lt;|&gt;&gt;)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.ly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(;)</string>
			<key>name</key>
			<string>keyword.operator.semi-colon.ly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(,)</string>
			<key>name</key>
			<string>punctuation.definition.comma.ly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([.])</string>
			<key>name</key>
			<string>punctuation.definition.dot.ly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(:)</string>
			<key>name</key>
			<string>punctuation.definition.colon.ly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[|\]|{|}|\(|\))</string>
			<key>name</key>
			<string>punctuation.definition.bracket.ly</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>string_escaped_char</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(\\|[abfnrtv'"]|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|U[0-9a-fA-F]{8}|[0-7]{3})</string>
					<key>name</key>
					<string>constant.character.escape.ly</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.unknown-escape.ly</string>
				</dict>
			</array>
		</dict>
		<key>string_placeholder</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x)%
                        (\d+\$)?                                    # field (argument #)
                        [#0\- +']*                                  # flags
                        [,;:_]?                                     # separator character (AltiVec)
                        ((-?\d+)|\*(-?\d+\$)?)?                     # minimum field width
                        (\.((-?\d+)|\*(-?\d+\$)?)?)?                # precision
                        [diouxXDOUeEfFgGaAcCsSqpnvtTbyYhHmMzZ%]     # conversion type
                    </string>
					<key>name</key>
					<string>constant.other.placeholder.ly</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ly</string>
	<key>uuid</key>
	<string>1caaa75c-b61d-11e2-ba93-138feb5db969</string>
</dict>
</plist>
