/* The following code was generated by JFlex 1.6.1 */

package org.lucylang.ljvm.parser;

import static org.lucylang.ljvm.parser.Token.Type.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>E:/Development/ljvm/tools/../src/main/java/org/lucylang/ljvm/parser/lexer.flex</tt>
 */
public class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\36\1\37\1\51\1\51\1\46\22\0\1\36\1\35\1\44"+
    "\4\0\1\50\1\22\1\23\1\31\1\27\1\25\1\30\1\41\1\32"+
    "\12\40\1\0\1\24\1\34\1\26\1\33\2\0\32\42\1\0\1\45"+
    "\2\0\1\43\1\0\1\2\1\47\1\7\1\42\1\10\1\4\1\42"+
    "\1\17\1\15\2\42\1\12\1\42\1\6\1\14\2\42\1\3\1\13"+
    "\1\11\1\5\1\1\1\16\3\42\1\20\1\0\1\21\7\0\1\51"+
    "\u1fa2\0\1\51\1\51\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\11\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\1\1\24\1\25\1\26"+
    "\1\27\1\1\1\26\7\2\1\30\1\2\1\31\1\0"+
    "\1\32\1\33\1\34\1\23\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\11\2\1\47"+
    "\1\50\1\51\1\52\2\2\1\53\1\54\1\55";

  private static int [] zzUnpackAction() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\322\0\374\0\u0126"+
    "\0\u0150\0\u017a\0\u01a4\0\u01ce\0\124\0\124\0\124\0\124"+
    "\0\124\0\124\0\u01f8\0\u0222\0\u0222\0\124\0\124\0\u024c"+
    "\0\u0276\0\u02a0\0\124\0\124\0\u0222\0\u02ca\0\124\0\u02f4"+
    "\0\124\0\124\0\u031e\0\u0348\0\u0372\0\u039c\0\u03c6\0\u03f0"+
    "\0\u041a\0\u0444\0\u046e\0\250\0\u0498\0\124\0\u02ca\0\124"+
    "\0\124\0\124\0\u02ca\0\124\0\124\0\124\0\124\0\124"+
    "\0\124\0\124\0\124\0\124\0\250\0\u04c2\0\u04ec\0\u0516"+
    "\0\u0540\0\u056a\0\u0594\0\u05be\0\u05e8\0\u0612\0\250\0\250"+
    "\0\250\0\250\0\u063c\0\u0666\0\250\0\250\0\250";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\5\1\10\1\5"+
    "\1\11\1\12\3\5\1\13\1\14\1\5\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\5\1\3\1\37\1\3\1\33\1\5\1\3\1\0"+
    "\37\40\1\41\4\40\1\42\1\43\1\44\3\40\53\0"+
    "\1\5\1\45\15\5\20\0\1\5\1\0\2\5\3\0"+
    "\1\5\3\0\17\5\20\0\1\5\1\0\2\5\3\0"+
    "\1\5\3\0\7\5\1\46\7\5\20\0\1\5\1\0"+
    "\2\5\3\0\1\5\3\0\1\5\1\47\2\5\1\50"+
    "\12\5\20\0\1\5\1\0\2\5\3\0\1\5\3\0"+
    "\13\5\1\51\3\5\20\0\1\5\1\0\2\5\3\0"+
    "\1\5\3\0\11\5\1\52\5\5\20\0\1\5\1\0"+
    "\2\5\3\0\1\5\3\0\2\5\1\53\14\5\20\0"+
    "\1\5\1\0\2\5\3\0\1\5\3\0\3\5\1\54"+
    "\13\5\20\0\1\5\1\0\2\5\3\0\1\5\3\0"+
    "\16\5\1\55\20\0\1\5\1\0\2\5\3\0\1\5"+
    "\30\0\1\56\63\0\1\35\1\57\36\0\1\60\51\0"+
    "\1\61\51\0\1\62\63\0\1\63\11\0\37\40\1\0"+
    "\4\40\3\0\3\40\3\64\1\65\1\66\1\64\1\67"+
    "\2\64\1\70\25\64\1\0\4\64\1\71\1\72\1\0"+
    "\1\73\1\74\40\0\1\41\13\0\2\5\1\75\14\5"+
    "\20\0\1\5\1\0\2\5\3\0\1\5\3\0\10\5"+
    "\1\76\6\5\20\0\1\5\1\0\2\5\3\0\1\5"+
    "\3\0\11\5\1\77\5\5\20\0\1\5\1\0\2\5"+
    "\3\0\1\5\3\0\5\5\1\100\11\5\20\0\1\5"+
    "\1\0\2\5\3\0\1\5\3\0\5\5\1\101\11\5"+
    "\20\0\1\5\1\0\2\5\3\0\1\5\3\0\12\5"+
    "\1\102\4\5\20\0\1\5\1\0\2\5\3\0\1\5"+
    "\3\0\4\5\1\103\12\5\20\0\1\5\1\0\2\5"+
    "\3\0\1\5\3\0\14\5\1\104\2\5\20\0\1\5"+
    "\1\0\2\5\3\0\1\5\3\0\4\5\1\105\12\5"+
    "\20\0\1\5\1\0\2\5\3\0\1\5\3\0\12\5"+
    "\1\106\4\5\20\0\1\5\1\0\2\5\3\0\1\5"+
    "\3\0\6\5\1\107\10\5\20\0\1\5\1\0\2\5"+
    "\3\0\1\5\3\0\7\5\1\110\7\5\20\0\1\5"+
    "\1\0\2\5\3\0\1\5\3\0\7\5\1\111\7\5"+
    "\20\0\1\5\1\0\2\5\3\0\1\5\3\0\7\5"+
    "\1\112\7\5\20\0\1\5\1\0\2\5\3\0\1\5"+
    "\3\0\11\5\1\113\5\5\20\0\1\5\1\0\2\5"+
    "\3\0\1\5\3\0\2\5\1\114\14\5\20\0\1\5"+
    "\1\0\2\5\3\0\1\5\3\0\7\5\1\115\7\5"+
    "\20\0\1\5\1\0\2\5\3\0\1\5\3\0\7\5"+
    "\1\116\7\5\20\0\1\5\1\0\2\5\3\0\1\5"+
    "\3\0\5\5\1\117\11\5\20\0\1\5\1\0\2\5"+
    "\3\0\1\5\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1680];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\11\1\6\11\3\1\2\11\3\1\2\11"+
    "\2\1\1\11\1\1\2\11\13\1\1\11\1\0\3\11"+
    "\1\1\11\11\23\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    class StringLiteralIdentifier {
        StringBuffer string = new StringBuffer();
        int line, column;
    }
    StringLiteralIdentifier stringLiteralIdentifier = new StringLiteralIdentifier();

    private Token token(Token.Type type) {
        return new Token(type, yyline, yycolumn, yytext());
    }

    private Token token(Token.Type type, String text) {
        return new Token(type, yyline, yycolumn, text);
    }

    private Token token(Token.Type type, String text, int line, int column) {
        return new Token(type, line, column, text);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 160) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token nextToken() throws java.io.IOException, ParserException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return token(EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new ParserException("unexpected character '" + yytext() + "'");
            }
          case 46: break;
          case 2: 
            { return token(ID, yytext());
            }
          case 47: break;
          case 3: 
            { return token(LCURLY);
            }
          case 48: break;
          case 4: 
            { return token(RCURLY);
            }
          case 49: break;
          case 5: 
            { return token(LPAREN);
            }
          case 50: break;
          case 6: 
            { return token(RPAREN);
            }
          case 51: break;
          case 7: 
            { return token(SEMICOLON);
            }
          case 52: break;
          case 8: 
            { return token(COMMA);
            }
          case 53: break;
          case 9: 
            { return token(ASSIGN);
            }
          case 54: break;
          case 10: 
            { return token(PLUS);
            }
          case 55: break;
          case 11: 
            { return token(MINUS);
            }
          case 56: break;
          case 12: 
            { return token(TIMES);
            }
          case 57: break;
          case 13: 
            { return token(DIV);
            }
          case 58: break;
          case 14: 
            { return token(GT);
            }
          case 59: break;
          case 15: 
            { return token(LT);
            }
          case 60: break;
          case 16: 
            { return token(NOT);
            }
          case 61: break;
          case 17: 
            { /* return */
            }
          case 62: break;
          case 18: 
            { return token(NEWLINE);
            }
          case 63: break;
          case 19: 
            { return token(NUMBER_LITERAL, yytext());
            }
          case 64: break;
          case 20: 
            { stringLiteralIdentifier.string.setLength(0); stringLiteralIdentifier.line=yyline; stringLiteralIdentifier.column=yycolumn; yybegin(STRING);
            }
          case 65: break;
          case 21: 
            { stringLiteralIdentifier.string.append(yytext());
            }
          case 66: break;
          case 22: 
            { throw new ParserException("Unterminated string at end of line");
            }
          case 67: break;
          case 23: 
            { yybegin(YYINITIAL); return token(STRING_LITERAL, stringLiteralIdentifier.string.toString(), stringLiteralIdentifier.line, stringLiteralIdentifier.column);
            }
          case 68: break;
          case 24: 
            { return token(IF);
            }
          case 69: break;
          case 25: 
            { return token(EQUAL);
            }
          case 70: break;
          case 26: 
            { return token(GEQ);
            }
          case 71: break;
          case 27: 
            { return token(LEQ);
            }
          case 72: break;
          case 28: 
            { return token(NEQ);
            }
          case 73: break;
          case 29: 
            { throw new ParserException("Illegal escape sequence \""+yytext()+"\"");
            }
          case 74: break;
          case 30: 
            { stringLiteralIdentifier.string.append('\r');
            }
          case 75: break;
          case 31: 
            { stringLiteralIdentifier.string.append('\f');
            }
          case 76: break;
          case 32: 
            { stringLiteralIdentifier.string.append('\n');
            }
          case 77: break;
          case 33: 
            { stringLiteralIdentifier.string.append('\t');
            }
          case 78: break;
          case 34: 
            { stringLiteralIdentifier.string.append('\"');
            }
          case 79: break;
          case 35: 
            { stringLiteralIdentifier.string.append('\\');
            }
          case 80: break;
          case 36: 
            { stringLiteralIdentifier.string.append('\b');
            }
          case 81: break;
          case 37: 
            { stringLiteralIdentifier.string.append('\'');
            }
          case 82: break;
          case 38: 
            { return token(VAR);
            }
          case 83: break;
          case 39: 
            { return token(FUNC);
            }
          case 84: break;
          case 40: 
            { return token(NONE);
            }
          case 85: break;
          case 41: 
            { return token(ELSE);
            }
          case 86: break;
          case 42: 
            { return token(TRUE);
            }
          case 87: break;
          case 43: 
            { return token(FALSE);
            }
          case 88: break;
          case 44: 
            { return token(WHILE);
            }
          case 89: break;
          case 45: 
            { return token(RETURN);
            }
          case 90: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
